# Generated by Django 2.2.1 on 2019-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baigeng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('use', models.BooleanField()),
                ('modified_time', models.DateField(auto_now=True)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('creator', models.CharField(max_length=100)),
                ('contact_creator', models.CharField(blank=True, max_length=100)),
                ('related_person', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, default=None, max_length=10)),
                ('source', models.CharField(blank=True, default=None, max_length=100)),
                ('rank', models.IntegerField()),
                ('rank_num', models.IntegerField()),
            ],
        ),
    ]
