# Generated by Django 2.2.1 on 2019-08-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoraMain', '0002_category_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
